version: '3'
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "${PORT}:80"
    volumes:
      - .:/app
    networks:
      - mean-net

networks:
  mean-net:
    driver: bridge
