version: '3'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:8888"
    volumes:
      - .:/app
    links:
      - mongodb
    networks:
      - mean-net
      - mean-backtest-net
  mongodb:
    image: 'mongo:latest'
    container_name: mean_mongodb
    env_file: .env
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # - MONGODB_ENABLE_ADMIN=false
    volumes:
      - './mongo-volume:/data/db'
    networks:
      - mean-backtest-net
volumes:
  mongodb_data:
    driver: local

networks:
  mean-net:
    driver: bridge
  mean-backtest-net:
